apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    # URL is set at runtime via bind mount from $HOME/grafana/provisioning
    # This fallback uses localhost which works with SSH tunnel
    url: http://localhost:9090
    isDefault: true
    orgId: 1
    editable: true
    version: 1
    basicAuth: false
    jsonData:
      timeInterval: "15s"
      httpMethod: "POST"
      manageAlerts: false
      prometheusType: "Prometheus"
      prometheusVersion: "2.40.0"
